version: '2'
services:
  refine:
    build:
      context: ./refine
    ports:
      - '3333:3333'
    environment:
      - REFINE_MEMORY=2G
  virtuoso:
    build: 
      context: ./virtuoso
    ports:
      - '8890:8890'